import { Dimensions, StyleSheet } from 'react-native';
import sd from '../../../utils/styleDictionary';

export const DoctorHomeStyles = (theme) => StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingBottom: 50,
    backgroundColor: theme.colors.background,
  },
  addPostButton: {
    alignSelf: 'center',
    backgroundColor: '#2F88D4',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginBottom: 15,
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  postContainer: {
    flexDirection: "column",
    alignItems: "flex-start",
    width: "100%",
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    marginVertical: 4,
    padding: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  postContent: {
    fontSize: 16,
    color: '#333333',
    marginBottom: 10,
    fontFamily: 'Poppins-Regular',
  },
  postImage: {
    width: '100%',
    height: 200,
    borderRadius: 10,
    marginTop: 10,
    resizeMode: 'cover',
  },
  postTimestamp: {
    fontSize: 12,
    color: '#888888',
    marginTop: 8,
    fontFamily: 'Poppins-Light',
  },
  noPostsText: {
    fontSize: 16,
    color: '#888888',
    textAlign: 'center',
    marginVertical: 20,
    fontFamily: 'Poppins-Italic',
  },
  input: {
    backgroundColor: '#F2F4F7',
    borderRadius: 10,
    padding: 10,
    fontSize: 15,
    color: '#333333',
    marginVertical: 10,
    fontFamily: 'Poppins-Regular',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 15,
  },
  pickImageButton: {
    backgroundColor: '#2EBB6D',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 15,
    alignItems: 'center',
  },
  pickImageButtonText: {
    color: 'white',
    fontSize: 14,
    fontFamily: 'Poppins-SemiBold',
  },
  title: {
    fontSize: sd.fontSizes.large,
  },
  postButton: {
    backgroundColor: '#2F88D4',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  postAuthor: {
    flex: 3,
    fontSize: sd.fontSizes.base,
    color: theme.colors.onSurface,
    marginLeft: 10,
  },
  postImage:{
    width: 50,
    height: 50,
    borderRadius: 10,
    marginTop: 10,
    
  },
  postContent: {
    fontSize: sd.fontSizes.medium,
    color: theme.colors.onSurface,
    marginTop: 10,
    marginBottom: 10,
    flex: 2,
  },
  postTimestamp: {
    fontSize: sd.fontSizes.small,
    color: theme.colors.onSurfaceVariant,
    marginLeft: 10,
    flex: 2,
  },
  postButtonText: {
    color: 'white',
    fontSize: 16,
    fontFamily: 'Poppins-SemiBold',
  },
  announcementContainer: {
    backgroundColor: sd.colors.white,
    marginBottom: 15,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
    padding: 10,
  },
  carouselContainer: {
    height: Dimensions.get('window').height / 4, // Keep a fixed height for carousel
    backgroundColor: '#f8f8f8',
    margin: 30,
    borderRadius: sd.borders.radiusXL,
  },
  fab: {
    position: 'relative',
    margin: 16,
    right: 0,
    bottom: 0,
    borderRadius: 50,
  },
  modalContainer: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 8,
    alignSelf: 'center',
    width: '90%',
  },
  title: {
    fontSize: sd.fontSizes.large,
    fontFamily: sd.fonts.semiBold,
    margin: 10,
    color: theme.colors.primary,
  },
  statusContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
  },
  statusItem: {
    flex: 1,
    alignItems: 'center',
    margin: 5,
  },
  statusLabel: {
    fontSize: sd.fontSizes.base,
    color: theme.colors.onSurface,
    fontFamily: sd.fonts.regular,
    textAlign: 'center',
    flex: 1,
  },
  statusContent: {
    fontSize: sd.fontSizes.large,
    color: theme.colors.onSurface,
    fontFamily: sd.fonts.semiBold,
    flex: 1,
  },
  // New styles for selected images
  imageContainer: {
    position: 'relative',
    marginRight: 0,
    padding: 10,
  },
  selectedImage: {
    width: 80,
    height: 80,
    borderRadius: 10,
    resizeMode: 'cover',
  },
  badge: {
    position: 'absolute',
    top: 5,
    right:  5,
    backgroundColor: 'red',
    zIndex: 100,
  },
  badgeText: {
    color: 'white',
    fontWeight: 'bold',
  },
  statusCardsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 10,
  },
  statusCardWrapper: {
    width: '48%',
  },
  statusCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    borderLeftWidth: 4,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  statusCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
  },
  statusIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#E3F2FD',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  statusTextContainer: {
    flex: 1,
  },
  statusCount: {
    fontSize: 22,
    fontFamily: 'Poppins-Bold',
    color: '#1976D2',
    marginBottom: 4,
  },
  statusLabel: {
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
    color: '#555',
  },
  loadingCard: {
    padding: 20,
    alignItems: 'center',
    marginVertical: 10,
  },
  loadingText: {
    marginTop: 10,
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
    color: '#666',
  },
});
