import { StyleSheet } from "react-native";
import sd from "../../../utils/styleDictionary";

export const SignInStyles = (theme) => StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    marginTop: 55,
    marginBottom: 10,
  },
  backButton: {
    padding: 15,
    backgroundColor: theme.colors.surfaceVariant,
    borderRadius: 12,
    width: 45,
    height: 45,
    alignItems: 'center',
    justifyContent: 'center',
    ...sd.shadows.level1,
  },
  headerTitleContainer: {
    padding: 10,
    marginRight: 10,
  },
  headerTitle: {
    fontSize: 15,
    color: theme.colors.primary,
    fontFamily: sd.fonts.medium,
    textAlign: 'right',
  },
  titleContainer: {
    paddingLeft: 30,
    marginTop: 50,
  },
  title: {
    fontSize: 45,
    fontFamily: "Poppins-SemiBold",
    lineHeight: 55,
    color: theme.colors.primary,
  },
  formContainer: {
    flexDirection: "column",
    marginVertical: 25,
    paddingLeft: 30,
    paddingRight: 30,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    borderRadius: 10,
    backgroundColor: theme.colors.surfaceVariant,
    marginVertical: 10,
    ...sd.shadows.level1,
  },
  inputField: {
    flex: 1,
    height: 50,
    fontSize: sd.fontSizes.medium,
    fontFamily: sd.fonts.light,
    paddingLeft: 10,
    top: 2,
    color: theme.colors.onSurface,
  },
  iconContainer: {
    padding: 10,
  },
  dropdownContainer: {
    height: 50,
    width: "100%",
    borderRadius: 12,
    backgroundColor: theme.colors.surfaceVariant,
    marginVertical: 10,
    fontSize: 13,
    fontFamily: sd.fonts.light,
    color: theme.colors.onSurfaceVariant,
    ...sd.shadows.level1,
  },
  dropdown: {
    fontFamily: sd.fonts.light,
    color: theme.colors.onSurfaceVariant,
    fontSize: 15,
    flex: 1,
    width: "100%",
    height: "100%",
    paddingHorizontal: 10,
    
  },
  signInButtonContainer: {
    height: 55,
    borderRadius: 40,
    marginTop: 20,
    marginHorizontal: 30,
    backgroundColor: theme.colors.primary,
    ...sd.shadows.level2,
  },
  signInButton: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 12,
  },
  signInText: {
    color: theme.colors.onPrimary,
    fontSize: 16,
    textAlign: "center",
    fontFamily: sd.fonts.medium,
    letterSpacing: 0.5,
  },
  disabledButton: {
    opacity: 0.7,
  },
  forgotPasswordText: {
    textAlign: "center",
    marginTop: 20,
    fontSize: 14,
    fontFamily: "Poppins",
    color: theme.colors.onSurface,
  },
  errorMessage: {
    color: "red",
    fontSize: 12,
    marginLeft: 5,
    fontFamily: "Poppins",
  },
});
